service: where-its-at

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

functions:
  getEvents:
    handler: dist/functions/getEvents.handler # Peka på dist, där JavaScript-filerna hamnar
    events:
      - http:
          path: /events
          method: GET

  orderTickets:
    handler: dist/functions/orderTickets.handler # Samma här
    events:
      - http:
          path: /order
          method: POST
